static const char UI[] = 
  "<!DOCTYPE html>\n"
  "<html>\n"
  "<head>\n"
  "<script>\n"
  "window.addEventListener('load', function () {\n"
  "  const sendData = form => {\n"
  "    var XHR = new XMLHttpRequest();\n"
  "\n"
  "    // Bind the FormData object and the form element\n"
  "    var FD = new FormData(form);\n"
  "\n"
  "    // Set up our request\n"
  "    XHR.open('PUT', form.action);\n"
  "\n"
  "    // The data sent is what the user provided in the form\n"
  "    XHR.send(FD);\n"
  "  }\n"
  "  \n"
  "  // Access the form element...\n"
  "  [...document.getElementsByClassName('switch')].forEach(\n"
  "    function(form) {\n"
  "     form.addEventListener('submit', function(event) {\n"
  "          event.preventDefault();\n"
  "\n"
  "          sendData(event.target);\n"
  "        });\n"
  "    });\n"
  "});\n"
  "\n"
  "</script>\n"
  "<style>\n"
  ".grid-container {\n"
  "  display: grid;\n"
  "  grid-template-columns: auto auto auto;\n"
  "  padding: 10px;\n"
  "  max-width: 200px;\n"
  "}\n"
  ".grid-item {\n"
  "  border: 1px solid rgba(0, 0, 0, 0.8);\n"
  "  padding: 20px;\n"
  "  font-size: 30px;\n"
  "  text-align: center;\n"
  "}\n"
  "</style>\n"
  "</head>\n"
  "<body>\n"
  "<div class='grid-container'>\n"
  "  <div class='grid-item'>Lautsprecher</div>\n"
  "  <div class='grid-item'>\n"
  "    <form class='switch' target='ignore' action='/2/1' method='put'>\n"
  "      <input type='hidden' name='state' value='on' />\n"
  "        <input type='submit' value='An' />\n"
  "    </form>\n"
  "  </div>\n"
  "  <div class='grid-item'>\n"
  "    <form class='switch' target='ignore' action='/2/1' method='put'>\n"
  "      <input type='hidden' name='state' value='off' />\n"
  "        <input type='submit' value='Aus' />\n"
  "    </form>\n"
  "  </div>\n"
  "  \n"
  "  <div class='grid-item'>Beleuchtung Wabenregal</div>\n"
  "  <div class='grid-item'>\n"
  "    <form class='switch' target='ignore' action='/2/2' method='put'>\n"
  "      <input type='hidden' name='state' value='on' />\n"
  "        <input type='submit' value='An' />\n"
  "    </form>\n"
  "  </div>\n"
  "  <div class='grid-item'>\n"
  "    <form class='switch' target='ignore' action='/2/2' method='put'>\n"
  "      <input type='hidden' name='state' value='off' />\n"
  "        <input type='submit' value='Aus' />\n"
  "    </form>\n"
  "  </div>\n"
  "</div>\n"
  "\n"
  "</body>\n"
  "</html>\n";
